### PR TITLE
fix detection of non-syntactic names in `object_overwrite_linter()`

### LINKED ISSUE #2346: Support non-syntactic names in `object_overwrite_linter()`
This will be obsolete with #2344 I think, since I use `get_r_string()` there so overwrites of non-syntactic names should also be caught.

This reminds me that could use some tests.

_Originally posted by @AshesITR in https://github.com/r-lib/lintr/pull/2342#issuecomment-1823892508_

### PR DESCRIPTION
**Pull request by AshesITR**
fixes #2346

### CODE REVIEW

File: R/object_overwrite_linter.R [hunk 1]
```diff
@@ -102,6 +102,8 @@ object_overwrite_linter <- function(
 
     assigned_exprs <- xml_find_all(xml, xpath_assignments)
     assigned_symbols <- get_r_string(assigned_exprs, "SYMBOL")
+    is_quoted <- startsWith(assigned_symbols, "`")
```
Comment (MichaelChirico) [inline R/object_overwrite_linter.R:105]: this won't catch assignments with ' or "

Comment (AshesITR) [reply R/object_overwrite_linter.R]: fixed. Won't bother with raw strings though.

Comment (AshesITR) [reply R/object_overwrite_linter.R:105]: Those weren't caught by the XPath before, because they are `//STR_CONST`. `get_r_string()` handles removal of `"`, `'` and even `r"()"`. I added tests for the first two cases.

Comment (MichaelChirico) [reply R/object_overwrite_linter.R:105]: > even r"()"

The whole original point of `get_r_string()` was to account for that! :smile: 

Almost surely there's at least one other linter using the same logic to find assigned symbols, probably that should be kept in sync. But also I'm sure there's dozens of such cases in our code base by now of XPaths with 99% overlap that should be relegated to helpers.

File: R/object_overwrite_linter.R [hunk 2]
```diff
@@ -76,7 +76,7 @@ object_overwrite_linter <- function(
   # test that the symbol doesn't match an argument name in the function
   # NB: data.table := has parse token LEFT_ASSIGN as well
   xpath_assignments <- glue("
-    //SYMBOL[
+    (//SYMBOL | //STR_CONST)[
```
Comment (MichaelChirico) [inline R/object_overwrite_linter.R:79]: I wonder about the performance of `//STR_CONST` vs. `//LEFT_ASSIGN`. Actually per the original issue about avoiding `//expr`, they appear at roughly the same frequency, so probably it's not much difference.

https://github.com/r-lib/lintr/issues/1358#issue-1260855389

**Review by MichaelChirico — APPROVED** [review]

**Comment by MichaelChirico** [comment]
I reproduce the `link-rot` issue with `ess.r-project.org` on my local browser, but I assume this is a transient issue. Ignoring for now.

File: R/object_overwrite_linter.R (hunk 2 above)
Comment (AshesITR) [reply R/object_overwrite_linter.R:79]: Yeah, from what I remember, only `//expr` stood out to be exceptionally bad cost-wise.
