### PR TITLE
Fix `is_excluded_file()` again

### LINKED ISSUE #1442: file-specific linter exclusions error
I have a package with `./tests/testthat/test-style.R` and `R/style.R` and am trying to use the file/linter-specific exclusion setup described here: https://lintr.r-lib.org/articles/lintr.html#excluding-files-completely

If I have a .lintr config at package-root with the contents:

```
linters: linters_with_defaults()                                                                                             
exclusions: list(                                                                                                                    
    "tests/testthat/test-style.R" = list(semicolon_linter = Inf)                                                                                           
  )
```

The following error arises:

```
Error in file_exclusion[[names2(file_exclusion) == ""]] : 
  attempt to select less than one element in integerOneIndex
```

This results from the following call (from lintr::lint_dir):

```
path <- "/home/me/blah"
files <- file.path(path, c("R/style.R", "tests/testthat.R", "tests/testthat/test-style.R"))
exclusions <- list(list(semicolon_linter = Inf))
names(exclusions) <- file.path(path, "tests/testthat/test-style.R")

lintr:::drop_excluded(files, exclusions)
#> Error in file_exclusion[[names2(file_exclusion) == ""]] : 
#>   attempt to select less than one element in integerOneIndex
```

Apologies if I've misunderstood this new exclusions syntax.

### PR DESCRIPTION
**Pull request by AshesITR**
fixes #1442

### CODE REVIEW

File: tests/testthat/test-exclusions.R [hunk 1]
```diff
@@ -126,4 +126,48 @@ test_that("#1413: lint_dir properly excludes files", {
...
   expect_length(lint(file.path(tmp, "bad.R")), 0L)
   expect_length(lint_dir(tmp), 0L)
+
+})
+
+test_that("#1442: is_excluded_files works if no global exclusions are specified", {
+  withr::local_options(lintr.linter_file = "lintr_test_config")
+  tmp <- withr::local_tempdir()
+
+  writeLines(
```
Comment (MichaelChirico) [inline tests/testthat/test-exclusions.R:136]: we should write a local_lintr_config helper for this...
