### PR TITLE
`length(x):1` now mentions `rev()` in the lint message

### LINKED ISSUE #1542: seq_linter() gives the wrong message for n:1 lints
The result message should mention `rev()`, but currently it doesn't:

```
lint(text = ".N:1", linters = seq_linter())
# <text>:1:1: warning: [seq_linter] .N:1 is likely to be wrong in the empty edge case. Use seq_len(1) instead.
# .N:1
# ^~~~
```

It also says `seq_len(1)` instead of `seq_len(.N)`

### PR DESCRIPTION
**Pull request by MichaelChirico**
Closes #1542

### CODE REVIEW

**Review by AshesITR — DISMISSED** [review]

File: tests/testthat/test-seq_linter.R [hunk 1]
```diff
@@ -158,3 +158,12 @@ test_that("Message vectorization works for multiple lints", {
     seq_linter()
   )
 })
+
+test_that("Message recommends rev() correctly", {
+  linter <- seq_linter()
+
+  expect_lint(".N:1", rex::rex("Use rev(seq_len(.N))"), linter)
```
Comment (AshesITR) [inline tests/testthat/test-seq_linter.R:165]: BTW if this is data.table code, it should be `rev(.I)`.
Not correct in general, though, so the current message is fine I think.

**Review by AshesITR — APPROVED** [review]

File: tests/testthat/test-seq_linter.R (hunk 1 above)
Comment (MichaelChirico) [reply tests/testthat/test-seq_linter.R:165]: Good point. It also applies in the `1:.N` case, though, so I'll file it as a separate issue.
