### PR TITLE
missing_argument_linter ignores comments

### LINKED ISSUE #906: missing_argument_linter not working well with comment
Consider the following examples where missing argument actually presents:

```r
fun(
  1,
  2,
  # comment
)

fun(
  # comment
  ,
  1
)

fun(
  a = # comment
  ,
  1
)
```

but `missing_argument_linter` does not produce correct results.

### PR DESCRIPTION
**Pull request by renkun-ken**
Closes #906 

This PR makes `missing_argument_linter` ignores `COMMENT` nodes.

### CODE REVIEW

File: tests/testthat/test-missing_argument_linter.R [hunk 1]
```diff
@@ -77,4 +77,28 @@ test_that("returns the correct linting", {
   expect_lint("alist(a =)",
     list(message = rex("Missing argument in function call.")),
     missing_argument_linter(c()))
+
+  expect_lint("fun(
```
Comment (MichaelChirico) [inline tests/testthat/test-missing_argument_linter.R:81]: maybe add a comment saying why each test is here?

Comment (renkun-ken) [reply tests/testthat/test-missing_argument_linter.R:84]: done

**Comment by MichaelChirico** [comment]
IIUC this is dec-only so no NEWS needed. merge if that's correct

**Review by MichaelChirico — APPROVED** [review]

**Comment by MichaelChirico** [comment]
great catch btw!!
