### PR TITLE
Apply condition_call_linter() only on string literals

### LINKED ISSUE #2647: call. argument should not be added for custom conditions
`lintr::condition_call_linter()` will recommend the addition of `call.` even for custom conditions crafted with `errorCondition()` / `warningCondition()` when these don't support `call.=`.

``` r
stop(errorCondition("stop right there!", class = "custom_error_condition"))
#> Error: stop right there!

lintr::lint(
  text = "stop(errorCondition('stop right there!', class = 'custom_error_condition'))",
  linters = lintr::condition_call_linter()
)
#> <text>:1:1: warning: [condition_call_linter] Use stop(., call. = FALSE) not to display the call in an error message.
#> stop(errorCondition('stop right there!', class = 'custom_error_condition'))
#> ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

stop(errorCondition("stop right there!", class = "custom_error_condition"), call. = FALSE)
#> Warning in stop(errorCondition("stop right there!", class =
#> "custom_error_condition"), : additional arguments ignored in stop()
#> Error: stop right there!
```

<sup>Created on 2024-08-08 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

### PR DESCRIPTION
**Pull request by Bisaloo**
Fix #2647

### CODE REVIEW

File: R/condition_call_linter.R [hunk 1]
```diff
@@ -57,11 +57,15 @@
 #' @export
 condition_call_linter <- function(display_call = FALSE) {
   call_xpath <- glue::glue("
-    following-sibling::SYMBOL_SUB[text() = 'call.']
+    following-sibling::expr/STR_CONST
```
Comment (MichaelChirico) [inline R/condition_call_linter.R:60]: oh, sorry @Bisaloo this warrants a NEWS entry, please handle as a follow-up :)
