### PR TITLE
Omit anchor-esque pattern in string_boundary_linter()

### LINKED ISSUE #2636: Custom message fails for string_boundary_linter(), gives 'NA'
```r
lint('grepl("\\\\^", spec)\n', string_boundary_linter())
# <text>:1:7: warning: [string_boundary_linter] NA Doing so is more readable and more efficient.
# grepl("\\^", spec)
#       ^~~~~
```

### PR DESCRIPTION
**Pull request by MichaelChirico**
Closes #2636

### CODE REVIEW

File: R/string_boundary_linter.R [hunk 1]
```diff
@@ -98,12 +98,19 @@ string_boundary_linter <- function(allow_grepl = FALSE) {
 
   get_regex_lint_data <- function(xml, xpath) {
     expr <- xml_find_all(xml, xpath)
+    if (length(expr) == 0L) {
```
Comment (AshesITR) [inline R/string_boundary_linter.R:101]: Why short-circuit? This adds extra complexity later in the code.

File: R/string_boundary_linter.R [hunk 2]
```diff
@@ -98,12 +98,19 @@ string_boundary_linter <- function(allow_grepl = FALSE) {
...
     patterns <- get_r_string(expr)
     initial_anchor <- startsWith(patterns, "^")
     terminal_anchor <- endsWith(patterns, "$")
+    if (!any(initial_anchor) && !any(terminal_anchor)) {
+      return(NULL)
+    }
     search_start <- 1L + initial_anchor
     search_end <- nchar(patterns) - terminal_anchor
-    can_replace <- is_not_regex(substr(patterns, search_start, search_end))
+    can_replace <- (initial_anchor | terminal_anchor) &
```
Comment (AshesITR) [inline R/string_boundary_linter.R:112]: The variable name could be renamed to `should_lint` maybe?

File: tests/testthat/test-string_boundary_linter.R [hunk 3]
```diff
@@ -8,6 +8,10 @@ test_that("string_boundary_linter skips allowed grepl() usages", {
   # regex pattern --> no lint
   expect_no_lint("grepl('^[a-z]', x)", linter)
   expect_no_lint("grepl('[a-z]$', x)", linter)
+  # anchor-ish but not a regex --> no lint
```
Comment (AshesITR) [inline tests/testthat/test-string_boundary_linter.R:11]: Add issue reference to this regression test?

File: R/string_boundary_linter.R (hunk 1 above)
Comment (MichaelChirico) [reply R/string_boundary_linter.R]: I guess the efficiency benefit is not much. Reverted

**Review by AshesITR — APPROVED** [review]
