### PR TITLE
fix nested tidy function call indentation

### LINKED ISSUE #1898: `indentation_linter()` conflicts with `{styler}`
I am not sure if this is the same as https://github.com/tidyverse/style/issues/197, but here is another instance where `indentation_linter()` lints code that `{styler}` thinks is in line with the tidyverse style guide:

``` r
library(lintr)

"out <- data.frame(.ci_generic(x,
  ci = ci,
  ...
))" -> code

# styler won't change this code
styler::style_text(code)
#> out <- data.frame(.ci_generic(x,
#>   ci = ci,
#>   ...
#> ))

# but lintr will lint this code
lint(text = code, linters = indentation_linter())
#> <text>:2:2: style: [indentation_linter] Indentation should be 20 spaces but is 2 spaces.
#>   ci = ci,
#>  ^~~~~~~~~~
```

<sup>Created on 2023-01-11 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### PR DESCRIPTION
**Pull request by AshesITR**
Fixes #1898 

Works by adding a new `indent_type`  "suppress", which allows XPaths to detect indentation changes that should be suppressed for the specified style.

In the particular case we suppress indent changes from parentheses that start on the same line as their enclosed `expr` and where the enclosed expr has only one child on the final line (namely its closing parenthesis).

### CODE REVIEW

**Comment by AshesITR** [comment]
@IndrajeetPatil PTAL if this is an acceptable solution.

File: tests/testthat/test-indentation_linter.R [hunk 1]
```diff
@@ -632,6 +632,17 @@ test_that("hanging_indent_stlye works", {
...
+  # regression test for #1898
+  expect_lint(
+    trim_some("
+      outer_fun(inner_fun(x,
+        one_indent = 42L
+      ))
+    "),
+    NULL,
+    tidy_linter
+  )
```
Comment (IndrajeetPatil) [inline tests/testthat/test-indentation_linter.R:645]: This looks good to me, @AshesITR! Thanks for the quick fix.

Do you think we should include any of the following test cases?

``` r
library(lintr)

"outer_fun(inner_fun(
  x,
  one_indent = 42L
))" -> code

lint(code, linters = indentation_linter())

"outer_fun(inner_fun(x, # this is first arg
  one_indent = 42L # this is second arg
))" -> code

lint(code, linters = indentation_linter())

"outer_fun(
  inner_fun(
    x,
    one_indent = 42L
  )
)" -> code

lint(code, linters = indentation_linter())
```

<sup>Created on 2023-04-04 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Review by IndrajeetPatil — APPROVED** [review]
Thanks! 🙌
