### PR TITLE
Skip unloadable namespaces when populating imports

### LINKED ISSUE #1360: Breaking change (ish): lint_package() fails if loadNamespace() doesn't work for some deps
Finished a run of #1304 thanks to #1348 and am peeking at results now.

The first thing I'm noticing is that `lint_package()` fails on a lot of repos where it still succeeds on v2.0.1, in particular with error messages like:

```
[babette]: there is no package called ‘beastier’
[BiasCorrector] there is no package called ‘shiny’
[BTYDplus]: there is no package called ‘BTYD’
[caretEnsemble]: there is no package called ‘caret’
[cloudos]: there is no package called ‘ggplot2’
```

Haven't investigated why, but if this breaking change is intentional, we should mention it (I don't recall anything in the NEWS)

### PR DESCRIPTION
**Pull request by MichaelChirico**
Closes #1360

The tests are not very satisfying -- they basically just guarantee running `lint()` doesn't fail in this case.

Considered making a little "cache" to throw a warning, but opted for a long explanation in the documentation instead. I think that's a good compromise. See #1366 for a way forward on this.

### CODE REVIEW

File: R/namespace.R [hunk 1]
```diff
@@ -10,16 +10,29 @@ namespace_imports <- function(path = find_package()) {
...
 
-  # this loads the namespaces, but is the easiest way to do it
-  imports[full_imports] <- lapply(imports[full_imports], function(x) list(x, getNamespaceExports(asNamespace(x))))
+  imports[full_imports] <- lapply(imports[full_imports], safe_get_exports)
 
+  funs <- lapply(imports, `[[`, 2L)
   data.frame(
-    pkg = unlist(lapply(imports, function(x) rep(x[[1L]], length(x[[2L]])))),
-    fun = unlist(lapply(imports, `[[`, 2L)),
+    pkg = rep(unlist(lapply(imports, `[[`, 1L)), lengths(funs)),
```
Comment (AshesITR) [inline R/namespace.R:17]: Use `rep(full_imports, lengths(funs))` here after refactoring `safe_get_exports()` to return only the functions?

File: R/namespace.R [hunk 2]
```diff
@@ -10,16 +10,29 @@ namespace_imports <- function(path = find_package()) {
...
 
+# this loads the namespaces, but is the easiest way to do it
+# test package availablity to avoid failing out as in #1360
+#   typically, users are running this on their own package directories and thus
+#   will have the namespace dependencies installed, but we can't guarantee this.
+safe_get_exports <- function(ns) {
+  exports <- tryCatch(
+    getNamespaceExports(asNamespace(ns)),
+    error = function(cond) character()
+  )
```
Comment (AshesITR) [inline R/namespace.R:31]: Maybe better `if (requireNamespace(ns, quietly = TRUE))`?
Catchall tryCatch might be difficult to debug down the line.

File: R/object_name_linters.R [hunk 3]
```diff
@@ -24,6 +24,25 @@ object_name_xpath <- local({
...
+#'
+#' Suppose, for example, you have `import(upstream)` in your NAMESPACE,
+#'   which makes available its exported function
+#'   `a_really_quite_long_function_name` that you then use in your package.
+#'   Then, if `upstream` is not installed when this linter runs, a lint
+#'   will be thrown on this object (even though you don't "own" its name).
+#'
+#' There are three workarounds: (1) always namespace-qualify usages,
+#'   because this linter ignores names in `pkg::foo()` form; (2) use
+#'   `@importFrom(pkg, foo)` instead of a blanket `import(pkg)` in your
```
Comment (AshesITR) [inline R/object_name_linters.R:41]: Mixed roxygen / NAMESPACE syntax.

File: R/object_name_linters.R [hunk 4]
```diff
@@ -24,6 +24,25 @@ object_name_xpath <- local({
...
+#'   If this fails (e.g., the package is not yet installed), the linter
+#'   won't be able to ignore such usages.
+#'
+#' Suppose, for example, you have `import(upstream)` in your NAMESPACE,
+#'   which makes available its exported function
+#'   `a_really_quite_long_function_name` that you then use in your package.
+#'   Then, if `upstream` is not installed when this linter runs, a lint
+#'   will be thrown on this object (even though you don't "own" its name).
+#'
+#' There are three workarounds: (1) always namespace-qualify usages,
```
Comment (AshesITR) [inline R/object_name_linters.R:39]: Options?

File: R/object_name_linters.R [hunk 5]
```diff
@@ -24,6 +24,25 @@ object_name_xpath <- local({
...
+#'   because this linter ignores names in `pkg::foo()` form; (2) use
+#'   `@importFrom(pkg, foo)` instead of a blanket `import(pkg)` in your
+#'   NAMESPACE, because this linter takes these imported names as given;
+#'   and of course (3) install the package so that it's available in
```
Comment (AshesITR) [inline R/object_name_linters.R:43]: Make this the first option?

File: tests/testthat/dummy_packages/missing_dep/R/foo.R [hunk 6]
```diff
@@ -0,0 +1,7 @@
+downstream <- function() {
+  a_really_really_long_local_object_name <- 1
+  aSilLLyObjEctNaME <- 2
+
+  myFancyUpstream::upstreams_really_long_imported_object_name()
+  myFancyUpstream::uPStreams_SilLY.objecT.Name()
```
Comment (AshesITR) [inline tests/testthat/dummy_packages/missing_dep/R/foo.R:6]: Also add a case of `importFrom()`?

File: R/namespace.R (hunk 1 above)
Comment (MichaelChirico) [reply R/namespace.R:17]: Sorry, not seeing it...

(1) we get a list with elements like (a) `list(ns, imported_funs)` or (b) `list(ns)`
(2) `safe_get_exports()` fills out the (b)-type elements to match the style of (a)-type
(3) combine to get the output data.frame

the presence of the (a)-type elements makes it harder to refactor, but I may be missing something.

File: R/namespace.R (hunk 2 above)
Comment (MichaelChirico) [reply R/namespace.R:31]: also reads better, now that I've resigned myself to this being the right approach :)

File: tests/testthat/dummy_packages/missing_dep/R/foo.R (hunk 6 above)
Comment (MichaelChirico) [reply tests/testthat/dummy_packages/missing_dep/R/foo.R:6]: oh, good call. turns out we need to skip more... need to investigate further:

https://github.com/r-lib/lintr/blob/cc9a221763ffe01492eb3b4672915a78ea8c67f9/R/namespace.R#L29

File: R/namespace.R (hunk 1 above)
Comment (AshesITR) [reply R/namespace.R:17]: ah nevermind, I didn't see the named import part because it wasn't in the diff.

File: R/object_name_linters.R [hunk 7]
```diff
@@ -24,6 +24,27 @@ object_name_xpath <- local({
...
+#'   will be thrown on this object (even though you don't "own" its name).
+#'
+#' There are three options to get lintr to work correctly:
+#'   (1) install the package so that it's available in
+#'   the session where this linter is running; (2) always namespace-qualify
+#'   usages, because this linter ignores names in `pkg::foo()` form; and
+#'   (3) use `importFrom(pkg, foo)` instead of a blanket `import(pkg)` in your
+#'   NAMESPACE, because this linter takes these imported names as given;
+#'   and of course (3) install the package so that it's available in
+#'   the session where this linter is running.
```
Comment (AshesITR) [inline R/object_name_linters.R:46]: (3) appears twice now.
Also, what about using a md enumeration?

1. install the package so that it's available to this linter while it's running.
2. only use namespace-qualified functions, e.g. `pkg::foo()`, because they are ignored by this linter.
3. only use selective imports (`importFrom(pkg, foo)`) instead of wildcard imports (`import(pkg)`) in your `NAMESPACE`, because these are always assumed to be available by this linter.

Comment (MichaelChirico) [reply R/object_name_linters.R]: NVM, I think this list is wrong anyway. Resolving.

File: R/namespace.R (hunk 1 above)
Comment (MichaelChirico) [reply R/namespace.R]: Reworked now, PTAL.

**Review by AshesITR — APPROVED** [review]
