### PR TITLE
safer Lint(), xml_nodes_to_lints() and lint()

### LINKED ISSUE #1427: Invalid parentheses can cause lintr to error or hang
### Steps to reproduce
Run `lintr::lint()` on the following snippets.

This one throws `Error in rep.int(character, length) : invalid 'times' value`:
```r
function() {)
```

This one hangs forever:
```r
{ if (x) x()
```

### Expected behavior
The function should exit cleanly and report a human-readable error.

### Notes
Tested on version `3.0.0` released to CRAN as well as the development version at commit `6c3f0fd`.

### PR DESCRIPTION
**Pull request by AshesITR**
fixes #1427, and ensures an easier debugging experience because `Lint()` errors immediately on `NA` in `ranges`.
`xml_nodes_to_lints()` uses default values if the location XPaths fail to return a number.
This could also be made an error. WDYT?

Note that the current fallback solution doesn't guarantee col1 <= column_number <= col2.
Do we want to enforce this as well?

### CODE REVIEW

File: R/get_source_expressions.R [hunk 1]
```diff
@@ -83,7 +83,7 @@ get_source_expressions <- function(filename, lines = NULL) {
   source_expression$content <- get_content(source_expression$lines)
   parsed_content <- get_source_expression(source_expression, error = function(e) lint_parse_error(e, source_expression))
 
-  if (inherits(e, "lint") && (is.na(e$line) || !nzchar(e$line))) {
+  if (inherits(e, "lint") && (is.na(e$line) || !nzchar(e$line) || e$message == "unexpected end of input")) {
```
Comment (AshesITR) [inline R/get_source_expressions.R:86]: This fixes the `"{ if (x) x()"` case.

File: R/indentation_linter.R [hunk 2]
```diff
@@ -181,7 +181,7 @@ indentation_linter <- function(indent = 2L, hanging_indent_style = c("tidy", "al
       }
       change_begin <- as.integer(xml2::xml_attr(change, "line1")) + 1L
       change_end <- xml2::xml_find_num(change, xp_block_ends)
-      if (change_begin <= change_end) {
+      if (isTRUE(change_begin <= change_end)) {
```
Comment (AshesITR) [inline R/indentation_linter.R:184]: This fixes `"function() {)"` for `indentation_linter()`.

File: R/xml_nodes_to_lints.R [hunk 3]
```diff
@@ -61,17 +61,29 @@ xml_nodes_to_lints <- function(xml, source_expression, lint_message,
...
 
   lines <- source_expression[["lines"]]
   if (is.null(lines)) lines <- source_expression[["file_lines"]]
 
   if (xml2::xml_attr(xml, "line2") == line1) {
     col2 <- xp_find_location(xml, range_end_xpath)
+    if (is.na(col2)) {
+      warning("Could not find range end for lint. Defaulting to width 1.")
+      col2 <- col1
+    }
```
Comment (AshesITR) [inline R/xml_nodes_to_lints.R:77]: This fixes `"function() {)"` for `function_left_parentheses_linter()`.

**Comment by AshesITR** [comment]
Related to #763 as well.
Might do this together.

**Comment by AshesITR** [comment]
Funny how many bugs this change uncovered in our own codebase 😅

File: R/indentation_linter.R [hunk 4]
```diff
@@ -231,7 +231,10 @@ indentation_linter <- function(indent = 2L, hanging_indent_style = c("tidy", "al
       lint_lines <- unname(as.integer(names(source_expression$file_lines)[bad_lines]))
       lint_ranges <- cbind(
         pmin(expected_indent_levels[bad_lines] + 1L, indent_levels[bad_lines]),
-        pmax(expected_indent_levels[bad_lines], indent_levels[bad_lines])
+        pmin(
+          pmax(expected_indent_levels[bad_lines], indent_levels[bad_lines]),
+          nchar(source_expression$file_lines[bad_lines]) + 1L
+        )
```
Comment (AshesITR) [inline R/indentation_linter.R:237]: If the expected indent is larger than the current line width, the lint range would become invalid.

File: R/indentation_linter.R [hunk 5]
```diff
@@ -241,7 +244,12 @@ indentation_linter <- function(indent = 2L, hanging_indent_style = c("tidy", "al
         type = "style",
         message = lint_messages,
         line = unname(source_expression$file_lines[bad_lines]),
-        ranges = apply(lint_ranges, 1L, list, simplify = FALSE)
+        ranges = lapply(
+          seq_along(bad_lines),
+          function(i) {
+            list(lint_ranges[i, ])
+          }
+        )
```
Comment (AshesITR) [inline R/indentation_linter.R:252]: `apply(..., simplify = FALSE)` is R >= 4.1, so we need to use `lapply()` instead.

File: tests/testthat/test-methods.R [hunk 6]
```diff
@@ -42,7 +42,7 @@ test_that("as.data.frame.lints", {
       type = "error",
       message = "Under no circumstances is the use of foobar allowed.",
       line = "a <- 1",
-      ranges = list(c(1L, 2L), c(10L, 20L))
+      ranges = list(c(1L, 2L), c(6L, 7L))
```
Comment (AshesITR) [inline tests/testthat/test-methods.R:45]: Previous second range was invalid.

File: tests/testthat/test-rstudio_markers.R [hunk 7]
```diff
@@ -40,7 +40,7 @@ test_that("it returns markers which match lints", {
       Lint(
         filename = "test_file2",
         line_number = 10L,
-        column_number = 5L,
+        column_number = 1L,
```
Comment (AshesITR) [inline tests/testthat/test-rstudio_markers.R:43]: line defaults to `""`, so only `column_number = 1L` is valid.

**Comment by AshesITR** [comment]
@IndrajeetPatil @MichaelChirico this is ready for review now, I think.

File: R/get_source_expressions.R [hunk 8]
```diff
@@ -152,6 +152,19 @@ lint_parse_error <- function(e, source_expression) {
   lint_parse_error_nonstandard(e, source_expression)
 }
 
+fixup_line <- function(line) {
+  # helper to ensure a valid string is provided as line where necessary handles tow cases:
```
Comment (MichaelChirico) [inline R/get_source_expressions.R:156]: i'm not understanding this comment, some typos?

> handles tow cases

File: R/get_source_expressions.R [hunk 9]
```diff
@@ -152,6 +152,19 @@ lint_parse_error <- function(e, source_expression) {
...
+  #  * NA lines, as generated by running outside of code blocks in Rmd documents
+  #  * invalid string lines, as generated by invalid encoding settings
+  if (is.na(line)) {
+    return("")
+  }
+  tryCatch({
```
Comment (MichaelChirico) [inline R/get_source_expressions.R:162]: Nit: for readability I might prefer s.t. like

```r
nchar_fails <- inherits(tryCatch(nchar(line, type = "chars"), error = identity), "error")
if (nchar_fails) {
  ""
} else {
  line
}
```

Or something along those lines. Now it might be tricky/require some mental cache to figure out what's actually being returned, and the construct of having two statements in the `tryCatch()` when only the first is expected to cause issues might be confusing (though I often use it myself and I'm sure it's used elsewhere in our sources...)

WDYT?

File: R/get_source_expressions.R (hunk 8 above)
Comment (MichaelChirico) [inline R/get_source_expressions.R:156]: nit: I often write internal helpers' docs as roxygen2 style with `@noRd` tag

File: R/get_source_expressions.R [hunk 10]
```diff
@@ -172,23 +185,27 @@ lint_parse_error_r43 <- function(e, source_expression) {
...
-  if (line < 1L || line > length(source_expression$lines)) {
+  if (line_number < 1L || line_number > length(source_expression$lines)) {
     # Safely handle invalid location info
-    line <- 1L
+    line_number <- 1L
     column <- 1L
   }
 
+  line <- fixup_line(source_expression$lines[[line_number]])
+  if (column == 0L || column > nchar(line) + 1L) {
```
Comment (MichaelChirico) [inline R/get_source_expressions.R:198]: nit: it gives me some pause to see `nchar()` run 3 times, but I think it's fine b/c there's only one line here and this is only run once/file, is that right?

File: R/indentation_linter.R (hunk 4 above)
Comment (MichaelChirico) [reply R/indentation_linter.R:237]: worth leaving as a comment?

File: R/indentation_linter.R (hunk 5 above)
Comment (MichaelChirico) [reply R/indentation_linter.R:252]: leave a comment for several years later when we can depend on R>=4.1?

File: R/lint.R [hunk 11]
```diff
@@ -402,6 +402,18 @@ Lint <- function(filename, line_number = 1L, column_number = 1L, # nolint: objec
     )
   }
 
+  max_col <- max(nchar(line) + 1L, 1L, na.rm = TRUE)
+  if (is.na(column_number) || column_number < 0L || column_number > max_col) {
```
Comment (MichaelChirico) [inline R/lint.R:406]: since `Lint()` is exported, let's check `length(column_number) != 1L` as well?

File: R/lint.R [hunk 12]
```diff
@@ -402,6 +402,18 @@ Lint <- function(filename, line_number = 1L, column_number = 1L, # nolint: objec
     )
   }
 
+  max_col <- max(nchar(line) + 1L, 1L, na.rm = TRUE)
```
Comment (MichaelChirico) [inline R/lint.R:405]: Also check `length(line) > 0` to ensure `length(max_col) > 0`

File: R/lint.R [hunk 13]
```diff
@@ -418,6 +430,12 @@ Lint <- function(filename, line_number = 1L, column_number = 1L, # nolint: objec
   obj
 }
 
+is_valid_range <- function(range, max_col) {
+  0L <= range[[1L]] &&
```
Comment (MichaelChirico) [inline R/lint.R:434]: maybe a `stopifnot(length(ranges) == 2L)`?

also why `range` vs `ranges` difference?

Comment (MichaelChirico) [reply R/lint.R:434]: oh nvm, I confused this with being the `check_ranges()` body

File: R/lint.R [hunk 14]
```diff
@@ -463,6 +481,23 @@ rstudio_source_markers <- function(lints) {
   out
 }
 
+check_ranges <- function(max_col, ranges) {
+  if (is.null(ranges)) {
+    return()
+  }
+  if (!is.list(ranges)) {
+    stop("`ranges` must be NULL or a list.")
+  } else if (!all(lengths(ranges) == 2L) || !all(vapply(ranges, is.numeric, logical(1L)))) {
```
Comment (MichaelChirico) [inline R/lint.R:490]: looks like we run 5-6 loops over `ranges`, how about

```r
if (!is.list(ranges)) {
  stop(...)
}
for (ii in seq_along(ranges)) check_range(ranges[[ii]])
```

and an individual range checker for each range that checks `length()`, `is.numeric()`, `anyNA()`, `is_valid_range()`?

File: tests/testthat/test-xml_nodes_to_lints.R [hunk 15]
```diff
@@ -86,6 +86,48 @@ test_that("it handles multi-line lints correctly", {
...
 
+test_that("it doesn't produce invalid lints", {
+  # Part of #1427
+  code <- "before   %+%   after"
+  tmpfile <- withr::local_tempfile(lines = code)
+  expr <- get_source_expressions(tmpfile)$expressions[[2L]]
+  xml <- expr$full_xml_parsed_content
+  node <- xml2::xml_find_first(xml, "//SPECIAL")
+
+  expect_warning(l_invalid_loc1 <- xml_nodes_to_lints(
```
Comment (MichaelChirico) [inline tests/testthat/test-xml_nodes_to_lints.R:97]: these tests require a lot of staring to figure out what's going on, any ideas for improvement? o/w a comment is needed

**Comment by MichaelChirico** [comment]
Thanks for this! Mostly nit-picky comments, sorry about that. 95% of the way there :crossed_fingers:

File: R/get_source_expressions.R (hunk 8 above)
Comment (AshesITR) [reply R/get_source_expressions.R:156]: Yeah, should be "two cases"
The problem is some situations can wind up with `line` being either `NA_character_` or containing an invalid multibyte character. Both of these will mess up the `Lint()` object, so need to be addressed.

**Comment by IndrajeetPatil** [comment]
> The linked issues are milestone 3.0.3, so moving this PR to 3.0.3 as well.

I'm confused now. From https://github.com/r-lib/lintr/issues/1476, I understood that there isn't going to be a `3.0.3` release; the next release will be `3.1.0`.

File: R/get_source_expressions.R (hunk 9 above)
Comment (AshesITR) [reply R/get_source_expressions.R:162]: Rewrote to 
```r
nchars <- tryCatch(nchar(line, type = "chars"), error = function(e) NA_integer_)
if (is.na(nchars)) {
  ""
} else {
  line
}
```

File: R/get_source_expressions.R (hunk 10 above)
Comment (AshesITR) [reply R/get_source_expressions.R:198]: This is only called once per file and only if a parse error occurred in that file.
Also, one of the `nchar()` calls could only be avoided by complicating the return value of `fixup_line()` to also return `nchar(line)`, or 0.

All in all, I don't really think this is worth the effort.

Comment (MichaelChirico) [reply R/get_source_expressions.R:209]: Agreed, thanks for confirming.

File: R/get_source_expressions.R [hunk 16]
```diff
@@ -152,6 +152,30 @@ lint_parse_error <- function(e, source_expression) {
...
+#'
+#' [nchar()] can detect both cases: 1. returns `NA_integer_`, 2. errors
+#'
+#' @param line Possibly misencoded or NA line
+#'
+#' @return `line` if it's a valid non-NA string, otherwise an empty string.
+#'
+#' @noRd
+fixup_line <- function(line) {
+  nchars <- tryCatch(nchar(line, type = "chars"), error = function(e) NA_integer_)
```
Comment (MichaelChirico) [inline R/get_source_expressions.R:171]: tempting to use `NA` here, since we're only checking `is.na()`, since technically `logical` type _could_ be smaller than integer... OTOH maybe `NULL` would allocate even less space. OTOOH this doesn't really matter. Moving on.

File: R/lint.R [hunk 17]
```diff
@@ -382,7 +382,7 @@ reorder_lints <- function(lints) {
 #' Create a `lint` object
 #' @param filename path to the source file that was linted.
 #' @param line_number line number where the lint occurred.
-#' @param column_number column number where the lint occurred.
+#' @param number column number where the lint occurred.
```
Comment (MichaelChirico) [inline R/lint.R:385]: is that intentional? this would be a user-facing API change? I guess this is by mistake...

File: R/lint.R [hunk 18]
```diff
@@ -418,6 +433,35 @@ Lint <- function(filename, line_number = 1L, column_number = 1L, # nolint: objec
   obj
 }
 
+is_number <- function(number, n = 1L) {
+  length(number) == n && is.numeric(number) && !anyNA(number)
```
Comment (MichaelChirico) [inline R/lint.R:437]: TIL `length()` is ever-so-slightly faster & so is better to test first. nice!

File: R/get_source_expressions.R (hunk 16 above)
Comment (AshesITR) [reply R/get_source_expressions.R:171]:
``` r
pryr::object_size(NA)
#> 56 B
pryr::object_size(NA_integer_)
#> 56 B
```

<sup>Created on 2022-12-08 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I'd prefer type safety (`nchars` is always an integer) instead of code brevity here.
