### PR TITLE
simplify object_usage helper function, fix error

### LINKED ISSUE #1081: object_usage_linter doesn't catch assignments with =
Noticed while working on #1078.

Compare

```
  expect_lint(
    trim_some("
      fun <- function() {
        a <- 1
      }
    "),
    rex("local variable", anything, "assigned but may not be used"),
    linter
  )
```

and

```
  expect_lint(
    trim_some("
      fun = function() {
        a = 1
      }
    "),
    rex("local variable", anything, "assigned but may not be used"),
    linter
  )
```

The latter test fails on HEAD because the xpath for `=` assignments is wrong. Fix forthcoming.

### PR DESCRIPTION
**Pull request by MichaelChirico**
Closes #1081

### CODE REVIEW

File: R/object_usage_linter.R [hunk 1]
```diff
@@ -188,31 +188,26 @@ get_assignment_symbols <- function(xml) {
...
-  left_assignment_functions <-
-    xml2::xml_find_all(xml, "expr[LEFT_ASSIGN][expr[2][FUNCTION]]/expr[2]")
-  equal_assignment_functions <-
-    xml2::xml_find_all(xml, "equal_assign[expr[2]][expr[FUNCTION]]/expr[2]")
-  assign_assignment_functions <-
-    xml2::xml_find_all(xml, "expr[expr[SYMBOL_FUNCTION_CALL/text()='assign']]/expr[3]")
-  setmethod_assignment_functions <-
-    xml2::xml_find_all(xml, "expr[expr[SYMBOL_FUNCTION_CALL/text()='setMethod']]/expr[3]")
+  direct_assignment_functions <-
+    xml2::xml_find_all(xml, "//*[((self::expr and LEFT_ASSIGN) or (self::expr_or_assign_or_help and EQ_ASSIGN)) and expr[2][FUNCTION]]/expr[2]")
```
Comment (MichaelChirico) [inline R/object_usage_linter.R:192]: we could also consider combining the two xpaths here to avoid calling `xml_find_all()` twice, but for now I left it for readability.

**Review by AshesITR — APPROVED** [review]
